#+title: Prologue
The shimmering moon passed over Misun's grey iris. She had been staring at it as it moved ever so-slightly for the past two hours, her usual nightly mediation.
The Light shot even brighter on her cheek from the left-- a silver, shiny globe, a hand or so wide, floated just a few feet above her, reflecting the Light. In in its center, which was hollowed out in a cross shape, a gray dull metal flowed-- and then transmuted into a brighter metal-- and then into a dark Liquid. Though its inner contents kept transforming, it was almost as if the globe stared with her, looking for something amongst the clouds.
She took a deep exhale. The villagers would be expecting her back and she didn't want to disturb their rest.
The curled leaves parted for her slow yet swift steps. The globe followed close behind, silently twisting around her. She pounced past compact cabins made of thick cut logs. The orchestra of crickets, frogs, and owls greeted her up to a much larger, rectangular cabin in the center of the circle of smaller cabins. She slid open the door, patched of flat sticks and reeds.
"Firestarter," the woman whispered to the globe, which followed her inside. It whirred, and its inner being transformed into a colorless Gas. She opened her hand-- a plume of fire stretched above her palm, as if an invisible torch was balancing on it. The Dark room illuminated to show long, wooden tables with wood stumps, some with dirty plates on them.
"Mexos? Lillia?" the woman whispered. Her hosts usually were around the fireplace at this time, but the cabin was silent and Dark. "Is anyone still awake?"
She turned around, directing the plume of fire to the edges of the cabin in a circular motion. A spotlight shone on log walls, mounted pelts, an unlit fireplace--
"Misun!" A masculine voice, Mexos, whispered from the far end of the cabin where the entrance to the bedrooms was. Misun turned and directed the fire in her hand towards the voice.
"Just stay there and be quiet. We're putting the kids to sleep," Mexos whispered. Misun could see his outline and tiptoed closer to him.
"Stay there! Turn off the Light!" Mexos hissed.
Misun raised an eyebrow. The middle-aged fisherman wasn't usually this nervous. She leaned forward, inspecting Mexos' face.
He turned around as soon as he did that. Why was he acting so closed off, despite being such an open host before?
Her eyes widened. She spun around and kicked behind her.
*THUMP. /Crash!.* /Something/, something invisible, slammed against the tables, sending plates clammoring to the floor.
"Steel!" Misun shouted at the globe-- she ducked beneath the tables just as two black blurs shot at where she'd been standing and smashed into the log walls. The globes' inner issence transformed into steel, and the next beat, the woman's skin transformed too.
Just as her skin had hardened, a slurry of acid /splashed/ against it. It burned into smoke.
Misun outstretched her hand, and the plume of continuous fire stretched out over the table. It lit up the room-- at once, before invisible, as if out of the void-- a figure manifested next to the table that had been shaken. It was a dark-haired man, and his eyes were fixed on the woman as he crouched just beside the table-- unhuman /red/ eyes, of rage and malice, as sharp as the curved black dagger he clutched in one hand. She knew those eyes well. They were Govoth's, and they had been hunting her for more than half her life.
The Light emanating from Misun's cone of fire stretched to fill the hall and another gaggle of other figures were revealed from the Darkness, Govoth's Illusion of an empty room now broken. Five men, /identical/ in appearance, with medium-length hair and thin, angular bodies, stood with their throwing arms back; she knew a man who looked like them to be Darzhir but did not know which, if any, were them. A woman with copper skin held a large glass backpack, filled with various materials and tubes, and floating from her fingers was the acid, impossibly hanging in the air. She knew this fellow Elemental to be Lilath. A pale, freckled woman-- Arelie-- crouched on the table, obviously focused on the intruder like the others, yet with wide eyes that betrayed a sense of unease. And at the far end, a scruffy, orange-bearded man, who she knew to be Tordin, stepped closer to the Light coming from the cone of fire-- and the Light shrank, as if being absorbed by his arm. A large smile grew on his face as he /himself/ grew.
Misun closed the tips of her fingers. The cone receded back towards her hand. Her friend and host, Mexos, was dead, as was his entire family and village. That man she had talked to was nothing but an Illusion of Govoth's, and if she hadn't trained to spot them for a lifetime, she would have been killed by the ambush which was also shielded by his Illusion. Inside, she wanted to weep for the family that had hosted her for months, but her mental discipline wouldn't let her-- she knew if they got what they came for, her and the sphere, Mexos and his village would be far from the last victim.
She raised a fist. The tables and floor smashed apart into planks and chips, being pushed up by the ground below which she commanded.
"So you want to play like that," a rough growl came from the Darkness.
Misun glanced to the rubble where Govoth was. He was nowhere to be found.
Where the growl had come from, several spherical glow of multicolor Light shined, dangling back and forth from a gaggle of glowing Crystals, all attatched to a necklace, the multicolor Light teasing the rough curled hairs of an orange beard.
/Zzzp./
The Light Crystals, and the body that held them, collapsed into a purple flash.
Misun was /kicked/ in the back, sending her flying into the rubble. Tordin, the orange-bearded man, had been teleported behind her by Arelie's touch. He smiled with sociopathic esctacy-- he had /grown/, and one of his Crystals no longer shone brightly, but was white and opaque-- in fact, they were all a bit dimmer.
He raised another leg and stomped. Misunraised two elbows in a cross and blocked the man's large bare foot. He screamed in fury, but a brutal smile burned from his mouth, and he grew even larger.
Metal bolts flew at her. She barely pushed them away with fast gusts of air and water, but Tordin seized her leg as she dodged one. He upended her and spun her around like a child with a doll, his massive frame growing with each spin. He slammed her against a tree.
She lept to her feet, readying a shield of thick air. The surroundings were pure Darkness-- an Illusion from Govoth. She got a line of poisonous Liquid from here chrome sphere, and slung it through the air. It searched for her attackers, reaching out as a sixth sense from her fingertips.
"/Uck!/" She heard her own grunt as a flurry of objects /cracked/ against her steel skin-- the Dahrzhirs' bolts. She yelped as one came /crashing/ into her, leaving a large dent in her thick metal skin. One just a bit faster, at a better angle, could pierce through.
Realizing she was surrounded, she formed a block of deeply compressed air and jumped upon it, making a staircase of airsteps for herself. Tordin shoved an elbow at her, and she met it with a sharp kick. He slid back, the balls of his feet digging into the dirt, and she landed in a deep squat, using the momentum of the fall to bounce back on her feet.
Darkness plastered her senses again. She had to keep moving to escape Govoth's grasp. She leaped into a sprint, using her Gas Heraldry to make airsteps in unexpected directions. There were brief flashes of Darkness and silence as Govoth tried to capture her location.
/BOOM!/ A steel bolt slammed into one of her airsteps, sending her to the ground.  She had to leap back to her feet charge and push through the fear and adrenaline wracking her brain.
She found stable vision again as she almost crashed against an evergreen tree. She had entered a patch of them, and communicated to her sphere to stay close behind. Govoth had lost track of her in the thicket, and she received no interruption to her senses. She had to act soon-- Tordin's footsteps shook the ground in the distance.
She snuck out from the tree, turning the bottom of her feet into plush to be quieter.
Focusing between the spots which she heard the identical men shuffling, she readied herself. She scanned the whole line of dense trees, knowing they were spread among them.
Four identical men, all behind different trees, jumped out at once. While they turned to her, she /burst/ into the air, scaling at the nearest one.
/Flt!/ /Flt!/ Thick needles burst through the air, threatening to destroy her airsteps again.
She pushed a mass of air through the center of her floating chrome sphere, and out the other side came green Liquid, which she moved through the air like whispy clouds. She turned her fingers downward and the Liquid flew down in two strands down towards the nearest attacker. He froze. Misun twisted her fingers and the strands of Liquid flew up his nostrils. He sputtered as his eyes turned bloodshot and the white foam of death bubbled from his lips.
The next identical man, a few dozen trees away, turned in panic and took out a whip from his belt. But the speed of her Liquid far outsped him.
*WHIP!* *WHIP!* The other identical men in a group of nearby trees cracked their long whips at Misun-- who jumped and dodged from them like a cat. She knew if they caught her once, she would be slowed to a halt.
Misun slid out from the tree, stretching tentacles of deadly Liquid out at the fleeing identical man. His skin melted into raw redness as it consumed him.
She turned to the remaining Dahrzhirs. They threw their whips again, and she dodged, this time sliding her forearm totally into water-- the whip splashed through, but she was prepared and held the Liquid together so it just passed through, deforming nothing and ensuring she didn't lose a drop. When she reforged her arm back to steel over flesh, not a piece was missing.
She reached her Liquid tentacles out, but she hadn't noticed Arelie had flashed in behind them. Misun shot out a wave of the poisonous Liquid. But by the Time it washed over, the two identical men and Arelie had vanished in a purple flash.
No matter. Misun heard Tordin's pounding close in on her from behind. His skin had been hardened, but not nearly as much as her steel. It was night and his Light powers would be much weaker by just relying on the Light stored in his Crystals, many of which were spent. And now they left him alone with her.
He charged and swung-- she jumped and turned the tip of her foot into the sharpest material she knew, diamond. That was finally enough to pierce the Tordin's skin. She ripped a hole in the back of his hand before leaping over his shoulder with an airstep. He howled.
But that was not the end of her assault. She sent a stream of Liquid to his fresh wound. Then the stream connected to his blood and pulled it out of his wound, which widened as his skin broke open. Tordin's hand crumpled and his scream tore through the trees.
Her senses turned Dark again-- Govoth had found her.
She heard the Tordin's footsteps slam towards her and dodged, but without her vision she could not find his wound. She could create another cone of fire to pierce Govoth's veil of Darkness, but it would just feed Light to the monstrous man and make him all the larger and more powerful. The monster hustled back as she raised a geyser of dirt.
She could not rely on her senses with the Govoth stalking her-- and he was the most difficult to find in battle. So, she would just have to rely on the feeling of her Heraldry, and the Space it created.
She called out to her chrome sphere mentally, it came to her, and touching its center, she pushed out a large string of corrosive Liquid. She made the Liquid into a massive serpentine whip, clearing areas where Tordin might have been, but she felt no disruption to her Liquid-- until she felt the end be /wrestled/ from her-- in a way that could only be done by another Liquid Herald.
She could /feel/ where it was being pulled, where the other Liquid Herald, Lilanth, was. Misun and Lilanth played tug-of-war-- Lilanth was powerful, but it was just foolish to go up against Misun on the Elemental field. And so letting Lilanth dig her heels in, Misun built up her her energy. She then /pushed/ the entire pool of poisonous Liquid right at Lilanth, releasing it at her arm.
Instinctively, Lilanth turned her whole arm into pure water-- a defense Misun had used many times before, that would protect it against any Liquid-- but only sealed her fate this time. Misun was ready  pushed a huge mass of pressurized Gas and shards of metal through Lilanth Liquid arm, sending the Liquid splashing.
Lilanth took a second to glance at her own arm, and only then screamed.
Misun tried to press forward, but her senses were blocked and she couldn't find any of her attackers without them.
She continued to make Space between her and her attackers by erupting large plumes of dirt, which she pushed forward with huge gusts of wind.
Misun called on her sphere to give her something better, some steel shards, but her sphere was not near her. She grasped for it again...
Nothing. She knew what had happened in an instant-- Arelie had teleported it somewhere far away. It was still connected to her, and made her much stronger, but without it near her she could ask it for no Elements. She called it back to her, but had no idea how far away it was and how long it would take for it to come back.
The confusion killed her focus on staying nimble in the Darkness. She bumped into a tree, and /yelped/ as something hit her in the shoulder. Even with steel skin, and a thick shield of air, a direct hit from the flying bullets thrown by the identical men pierced her.
She had to kill the Govoth soon if she even wanted to be able to defend herself. But how could she find him? As usual, she started with what she knew.
/He always was a coward... but he still liked to be on top.../
Her Mind lit up. She moved two stones from the ground that she felt into her hand. Sidestepping, she jumped up and made a spiral case of airsteps, ascending. She felt prickly pines brush against her steel skin.
She broke through the Illusion of Darkness and saw a /flash/ of the stars. Only for a moment, of course. She jumped, hopped, twirled and fell, glancing upon different treetops as she had brief frames where Govoth's veil of Darkness didn't catch her. The two stones in her palm scratched against each other astounding speed, making sparks fly. For a second, she saw a short figure crouched on the highest branch of a tree-- /she knew it./
Up here, she didn't need to worry about any Light powering Tordin-- but it was what she could use to finally defeat that veil of Darkness.
She pushed a powerful gust through the sparked stones, and a fireball lit above her hand. At once, the Illusion of blackness broke and her vision was restored. Less than a tree's length away, Govoth was crouched.
/That's it-- all this time-- you got him!/
The woman /blasted/ her fire forward, casting the red-eyed man in a blanket of fire.
She roasted him for what seemed like an eternity, balanced atop her step of pure air.
Finally, she let the fire shrink back to her hand. The treetops were still topped with flames, and she moved oxygen away from them to let it shrink.
But there was no skeleton.
/Fuck--/
The woman's eyes widened.
/An Illusion./
At once, she felt her body being /squeezed/-- She could make herself totally into Liquid or Gas, but that could destroy her body in one fell swoop-- and she didn't want what happened to Lilanth's arm to happen to her whole body.
She felt her body be pulled down to the ground-- and then stopped. Govoth let her see the truth for a moment-- she had been pulled down by Tordin and flashed through one of Arelie's Portals, and now was face-to-face with those shimmering red eyes.
Govoth grabbed her by the shoulders.
Misun jerked-- but it was too late. She disappeared from the world.


Misun spun around, her fists readied. She was blinded in a blur of light gray, a heavenly light compared to the utter Darkness she had been in before. Her metal body sunk through gravel floor--
She shifted her skin to flesh and found a stable position. She was on the side of a barren, rocky mountain, on a flat alcove. The environment was /lifeless/, and though there was a river on the mountain in the distance, it looked as if it did not flow.
She spun around instinctively, though there was no sound. Govoth greeted her from above.
"I'm sorry, Misun, but this is my world, and you're never going to get out. You are dead, now just accept it. I'll let you live a few minutes-- you can enjoy your last moments in peace," the red-eyed man said. "They say it's the last moments that really matter, and the surprises-- and for you this is both."
Misun grit her teeth. "I won't let you kill me. Even if my whole life is just making it so you can't return here, to disadvantage you-- I'll fight you every time."
Govoth clasped his lips. "I thought we could've reminsced over old times-- talk about our regrets, complain about /him/--"
Misun raised a hand, at loose rocks and boulders behind Govoth-- but they did not come loose as she expected.
Govoth smiled at her, before dissappearing.
She turned around, looking for her sphere. It was nowhere to be found. She reached out at the rocky mountain cliffside, expecting it to turn her skin. She squeezed the gravel and grunted. Her skin stayed flesh, and the Solids did not move.
She was powerless.
That warranted a scream at the vast dead hills behind her. The barren rocky highlands and grey smooth sky stretched for the entire horizon spoke back to her with uttersilence.
She only had a moment before she they reappeared. Govoth was back with the three tall, identical white men, a /massive/ Tordin, whose feet clung to the side of the mountain, separately from the alcove where the rest of them stood.
"As I was saying--," Govoth cleared his throat. "But so be it."
Tordin screamed-- he swung an arm the size of a small tree at the woman, who rolled into the gravel to avoid the attack.
She jumped down, her hands hanging off the cliff side opposite of the massive bearded man. Her brain had somehow told her body she was powerless-- she was red and sweaty with panic.
She looked below and dropped down, falling into a deep lunge and wincing. It may not have been matter, but it felt like it. She lunged into a quick sprint, only narrowly avoiding the large blurred bullets which came at her from the identical attackers above.
Tordin /slammed/ down from above, shaking the cliff. Misun pivoted like a panther.
"Honestly, just give up, Misun!" Govoth shouted as Misun ducked a swing from Tordin and returned a kick to his abdomen. "You don't have your little utility belt. And this is a world of pure Mind. You don't have /any/ Elements to grab from."
Misun snarled, jumping another blazing steel bolt from the identical Dahrzhirs as she ran past Tordin.
"Yeah. But you do," she spun and reached her arm out just as another steel bolt shot towards her. It /smashed/ into her arm-- sticking into her bone and sending a plume of blood and bone out on the other side of her forearm. She howled in agony, but from her arm her skin grew into steel.
A sinister smile appeared on the Govoth's face. "I always liked that you were disciplined enough to do the hardest things for the cause you believed in. But that was just meaningless pain. You can't beat us without an artifact, or without /real/ matter-- without options. And you forget, this is my realm. I still have power here."
In an instant, her surroundings became utter Darkness.
She shuffled around, her mind wracking her about the possibility of falling of the cliff.
"You've always been a coward! Even here facing me with /nothing/ and you still need your minions to get the job done!" she shouted.
There was no response. She was literally screaming into the void.
Two rough forces wrapped around each of her arms and /pulled./
She felt her body slow, her vicious twisting and fighting halting to a sad squirm. The identical Dahrzhirs were using their powers, flowing through their whips, to slow her down.
She felt a hand against her smooth steel back-- and then didn't, her touch also being cast into Darkness. She had been cast into the void.
/It's over, Misun. Relax. You don't need to put up that hard shell anymore./
She heard the words as if they were everywhere, as if they were whispered directly into her soul, as if she was the only Mind in existence.
/Relax. This is what you've always wanted, isn't it? To stop thinking. To stop fighting./
She was fading away. She truly felt nothing, she thought nothing, she was...
And then she felt it all again. He eyes popped into that bright Light, with that bearded ogre drolling above her, with those devilish red eyes inches from her face. Her ears filled with the pounding of her heart and the gasp of her lungs, she felt three hard blinks, and more than anything, a sharp pain in her chest that made every fluid in her body flow towards it.
She laid prone and could barely peek her chin up, but she knew that it was that black dagger lodged in her heart. She collapsed, unable to move.
/You know how I got them to beat you? It's the same way I knew how to find you./ The same voice laughed. /You drill over and over, you know every technique, but you always do things the same way, even after all this time./
Her skin started shifting to steel, from the edges of her arms up to her chest.
She could do it. Maybe it was soon enough to push the dagger out...
She always had the determination...
And there was no time more crucial then now...


Arelie looked distressed at Misun's half-steel corpse, the outer edges of her body chrome as if someone had melted a hole in the steel on her belly. The freckled woman was the only one who glanced back at it several times with nervous eyes, as the rest of the group was huddled under the moonlight, taking stock after the battle.
"What's the matter? You aren't-- isn't it good riddance? Isn't it relaxing that we've finally gotten one off the list?" Govoth said to Arelie, his pupils moving back and forth over her face.
"I don't know," the freckled woman said. "It's been-- so long, and we knew this was how it was going to end-- but she's one of the only ones who knew all of us, you know? And now there's one less."
The red-eyed man laughed. "You always thought too much," his voice raised so the rest of the group could hear him. "If you don't think this is a total win, you're insane!"
"It wasn't a /total/ win," Tordin said. He had already shrunk quite a bit, and held up a crumpled hand. "My left hand is destroyed."
"And I lost my arm," Lilanth motioned with her nub shoulder.
"And we lost... two of us," one of the Dahrzhirs said, and the others nodded.
"Tsk, tsk," Govoth said as he paced around the group. "Everyone says my eyes are red, but I've come to the conclusion their tint must actually be rose. Because it seems right now I'm the only one who can see... how beautiful things are gonna be for us."
The material inside the chrome orb, which followed Govoth, shifted to gold. The red-eyed man smiled as his skin did the same.
