#+title: Prologue
The shimmering white lotus dangling from the sparkled black blanket that was the night sky passed through the grey eyes of the dark-haired woman.
The Light shot even brighter on her cheek from the left-- a silver, shiny globe, a hand or so wide, floated just a few feet above her, reflecting the light. In in its center, which was hollowed out in a cross shape, a silverish yet dull metal flowed-- and then transmuted into a brownish, brighter metal-- and then into another form entirely...
The woman stayed still, her face and the globe being cast in darkness as the spotlight escaped behind the grey mist above. Though its inner contents kept transforming, it was almost as if the globe stared with her, looking for something amongst the clouds.
She continued on her path, the curled leaves parting for her slow yet swift steps, punctuated by each landing. The globe followed her, silently twisting around her.
She had a hard, yet full, austere beauty; her stature pressed upwards, yet one could tell tit was not a act, but the product of the support of her sturdy musculature.
She pounced past a couple of compact cabins made of thick cut logs. She stopped for another second, turning her ear towards them. The orchestra of crickets, frogs, and owls greeted her ear. She turned back to her path up to a much larger, rectangular cabin in the center of the circle of smaller cabins. She slid open the door, patched of flat sticks and reeds.
"Firestarter," the woman whispered to the globe, who had followed her inside. It whirred, and its inner being transformed into a colorless Gas. She opened her hand-- a plume of fire stretched just above her palm, as if an invisible torch was balancing on it. The dark room illuminated to show long, wooden tables with wood stumps, some with dirty stone plates on them.
"Mexos? Lillia?" the woman whispered as she stepped around the tables to the far side of the cabin. "Is anyone still awake?"
She turned around, directing her outstretched palm, which held the plume of fire in place, to the edges of the cabin in a circular motion. A spotlight shone on log walls, mounted pelts, an unlit fireplace--
She /whipped/ around-- her leg hooked in a arced kick--
*THUMP-- /Crash!.* /Something/-- something invisible-- slammed against the tables, sending plates clammoring to the floor.
"Steel!" the woman shouted at the globe-- she lunched back and duck beneath the height of the tables-- just as two black blurs /shot/ at where she'd been standing and SMASHED deep into the log walls. The globes' inner issence transformed into a hard, shiny metal-- and the next beat, the woman's skin was equally hard and shiny.
Just as her skin had hardened, a slurry of vomitish acid /splashed/ against the steel. It burned into smoke.
The dark-haired woman outstretched her hand, and the plume of continuous fire stretched out over the table. It was contained perfectly in a cone, set apart impossibly from its flammable surroundings. It lit up the room-- at once, before invisible, as if out of the void-- a figure manifested next to the table that had been shaken. It was a slightly short, dark-haired man, and his eyes were fixed on the woman as he crouched just beside the table-- literally, unhumanly, /red/ eyes, of rage and malice, as sharp as the curved black dagger he clutched in one hand.
The Light emanating from the cone stretched to fill the hall and the another gaggle of other figures jumped out from behind the tables-- five men, /identical/ in appearance, with medium-length brown hair and thin, angular white bodies, stood with their throwing arms back; a woman with copper skin held a large glass backpack, filled with various materials and various tubes, and floating from her fingers was that vomitish yellow acid, impossibly hanging in the air; a pale, freckled woman crouched on the table, obviously focused on the intruder like the others, yet with wide eyes that betrayed a sense of unease, and at the far end, a scruffy, orange-bearded man, stepped closer to the Light coming from the cone of fire-- the and the Light shrank, as if being absorbed into his arm, as he reached forward-- a large smile grew on his face as he /himself/ grew.
The dark-haired woman closed the tips of her fingers, and in response the cone receded back towards her hand. She faced her attackers with a raised fist--
The tables and floor smashed apart into planks and chips, being pushed up by the ground itself below.
"So you want to play like that," a rough growl came from the Darkness.
The dark-haired woman glanced to the rubble where the red-eyed man had been standing in front of. He was nowhere to be seen.
Where the growl had come from, several spherical glow of multicolor Light shined, dangling back and forth from a gaggle of glowing Crystals, all attatched to a necklace, the multicolor Light teasing the rough curled hairs of an orange beard.
/Zzzp./
The Light Crystals, and the body attatched to them, collapsed into a purple flash.
The dark-haired woman didn't spin around fast enough-- she was /kicked/ in the back, sending her flying into the rubble she had created.
The orange-beared man had appeared behind her, smiling with sociopathic esctacy-- he looked /bigger/, he /was/ bigger, and one of his Crystals no longer shone brightly, but was white and opaque-- in fact, they were all a bit dimmer.
He raised another leg and stomped down at her. Unable to fully get up in time, she raised two elbows in a cross and blocked the man's large bare foot. He screamed in fury, but a brutal smile burned from his mouth, and he grew even larger.
More metal bolts, barely visible they were flying through the air so fast, came at her.
She yelped as one came /crashing/ into her, ricocheting off and leaving a large dent in her thick metal skin. One just a bit faster, at a better angle, could pierce through.
She did a large circular kick, clearing the area for her. It smashed the massive man's arm.
He clutched it in agony. His scream tore through the rubble.
He grabbed her by the leg, and she wasn't fast enough. He upended her and spun her around like a child with a doll, his massive muscular frame growing with each spin. She shook her leg wildly and hardened more of it into steel, but his grip just hardened. A bright purple flashed in the corner of her eye. She saw it again as she spun around faster-- it was a growing oval. She flew into it--
She /whizzed/ out of it, spinning in Darkness, her head panicking for orientation--
*SMASH! Chhkk!* She felt her cranium and organs slam against stone. Her steel skin and bones sparked against a rock face.
She immeadiately jumped to her feet, readying an invisible shield of thick air in front of her. The surroundings were pure Darkness, but her chrome sphere had followed her. She got a line of poisonous Liquid from it, and slung it through the air. It searched for her attackers, reaching out as a sixth sense from her fingertips. She also tried to feel in the ground, moving around dirt connected by her feet, hoping to surprise them.
She held out a thick wall of Gas, shielding herself from attacks.  Her heart pounded. It would not be enough, she would have to find them soon, but she knew that every sound and movement was being shielded from her by the Dark Heraldry of the red-eyed man...
"/Uck!/" Almost on call, she heard her own grunt as a flurry of objects /cracked/ against her steel skin-- the lightning-fast silver bolts from those identical-looking throwers. Even her cloud of Gas was nothing to these bullets.  As much as it hurt, she kept her arm in the air, connected to the long string of poison. It was a coordinated attack, and she felt the other Elemental woman /grip/ on the end of her poisonous line of liquid, trying to wrestle control from her. But she was stronger, and she felt the usual surge of power from her sphere.
Realizing this wouldn't work, she released her grip on the Elements she was controlling. She jumped, creating a small cloud of thick Gas just under her feet, creating a virtual staircase pushing her upwards. She ran, doing this with ease in free form, moving up and down, left and right in the sky, and soon regained her senses. She heard objects whizzing past her, thrown by the identical men, and though it was late, the slight light of the moon gave her some vision. Up here, she also didn't have to worry about any teleporting attacks.
/Pound, pound, pound./ She looked down-- just as the massive man leaped up-- but even at over twelve feet tall, she just jumped over his arms and landed behind him, creating a new step for herself. She created a flurry of stairs going up as he twirled around, trying to smack at her--
She gasped as she fell-- a projectile came flying at the airstep she had made under her feet, pushing the compressed out in a million directions.
The massive bearded man shoved an elbow at her, and she met it with a sharp kick. He slid back, the balls of his feet digging into the dirt, and she turned her legs to land in a deep squat, using the momentum of the fall to bounce right back into a ready position.
Her vision was plastered with Darkness again, and she heard no sound except that which came from her mouth. The red-eyed man's Heraldry had caught her again. She had to keep moving to escape his grasp.
She leaped into a sprint, using her Gas Heraldry to push her strides in unexpected directions. She lessened the thickness of her steel skin layer so it wouldn't weigh her down. There were brief flashes of Darkness and silence, like her connection with reality was unstable as the red-eyed man tried to get a grip on her. The whizzing steel bullets that she had to dodge made her surroundings feel even more chaotic. But she had to find use what little her sense were giving her to find the hiding attackers if she ever hoped to turn the tide of the battle.
She turned to follow where the projectiles were coming from.
More projectiles came right at her, narrowly missing her. She had to charge and push through the fear wracking her brain-- she would push right through any Gas shields she made, even if they were effective against these lightning-speed bullets-- which they weren't.
She found stable vision again as she almost crashed against a tall evergreen tree. She had entered a slight patch of tall trees away from the and communicated to her sphere to follow her behind one. The red-eyed man had probably lost track of her in the thicket, and she received no interruption to her senses. She had to act soon-- the /pounding/ of the massive man's footsteps shook the ground not far behind.
"I know you're just waiting-- waiting for the right moment to bring a thousand of yourself here and kill them too! What's the matter? Too afraid to do it now? Or is it that even /you/ don't like you?" the dark-haired woman shouted.
There was a moment of silence-- she knew they were resisting the temptation to respond.
"Our own would dream of no such thing," one said.
"We wouldn't want to share the thrill and credit from killing you!" another shouted.
She snuck out from behind the tree, turning the bottom of her feet into plush to be quieter. Her chrome sphere hid behind her body.
Focusing between the spots which she heard them, she readied herself. She scanned the whole line of dense trees, knowing there were others waiting for her that weren't stupid enough to speak up.
Four identical men, all behind different trees, jumped out at once. In the moment where they were orientating themselves towards her, she /burst/ into the air, scaling at nearest one.
/Flt!/ /Flt!/ Thick needles burst through the air, threatening to destroy her airsteps again-- but this time she used the trees as extra objects to push herself off of.
She pushed a mass of air through the center of her floating chrome sphere, and out the other side came a mass of greenish liquid, which she moved through the air like whispy clouds. She turned her fingers downward and the green liquid flew down in two strands down towards the nearest attacker. He stood frozen, with no chance of getting away. The woman twisted her fingers upward and the strands of liquid flew up his nostrils. He sputtered as his eyes turned bloodshot and the white foam of death bubbled from his lips.
The next nearest identical man, a few dozen trees away, turned in panic and took out a whip from his belt. But the speed of her Liquid far outsped him. He tried in vain to whip her, but she ducked behind a tree.
*WHIP!* *WHIP!* The other identical men in a group of nearby trees cracked their long whips at the woman-- who jumped and dodged from them like a cat. She knew if they caught her once, she would be slowed to a pulp.
The dark-haired woman slid out from the tree, stretching tentacles of deadly Liquid out at the fleeing identical man. His skin melted into raw redness as it consumed him.
She turned to the remaining identical men. They threw their whips again, and she dodged, this time sliding her forearm totally into water-- the whip splashed through, but she was prepared and held the Liquid together so it just passed through, deforming nothing and ensuring she didn't lose a drop-- when she reforged her arm back to steel over flesh, not a piece was missing.
She reached her Liquid tentacles out towards them, but she hadn't noticed the freckled woman had flashed in behind them. Her and the dark-haired woman made eye contact and both froze for a moment. The dark-haired woman shot out a wave of the poisonous Liquid, a tsunami of demise. But by the Time it washed over, the two identical men and the freckled woman had vanished in a purple flash.
No matter. The dark-haired woman heard the massive man's pounding close in on her from behind. His skin had been hardened, but not nearly as much as her steel. It was night and his Light powers would be much weaker by just relying on the Light stored in his Crystals. And now they left him alone with her.
She rotated to face the quaking advance. The bearded man was nearly as tall as the trees now, but several of the Crystals hanging for his neck failed to emit Light.
He charged and swung-- she jumped and turned the tip of her foot into the sharpest material she knew-- diamond--
That was finally enough to pierce the bearded man's skin. She ripped a hole in the back of his hand before sliding over and through, leaping over his shoulder with an airstep. He howled.
But that was not the end of her assault. She focused her empty hands on his fresh wound. Though she was several feet away, she yanked blood out from his wound, widening it as his skin broke open. His hand crumpled and his scream tore through the trees.
Her senses turned Dark again-- the red-eyed man had found her.
She heard the monster's footsteps slam towards her and dodged, but without her vision she could not find his wound. She could create another cone of fire to pierce the red-eyed man's veil of Darkness, but it would just feed Light to the monstrous man and make him all the larger and more powerful. The monster hustled back as she raised a geyser of dirt.
She could not rely on her senses with the red-eyed man stalking her-- and he was the most difficult to find in battle. So, she would just have to rely on the feeling of her Heraldry, and the Space it created.
She called out to her chrome sphere mentally, it came to her, and touching its center, she pushed out a large string of corrosive Liquid. The sphere left her as the Liquid grew and attatched to her finger. She made it a massive serpentine whip, clearing areas where the massive man might have been, but she felt no disruption to her Liquid-- until she felt the end be /wrestled/ from her-- in a way that could only be done by another Liquid Herald.
She could /feel/ where it was being pulled, where the other Liquid Herald, the copper-skinned woman, was. She played tug-of-war with the woman, as she bounced back and forth to avoid the darts from the identical men she knew where flying at her. The other Liquid Herald was powerful, but this was just foolish, going up against the dark-haired woman on the Elemental field. And so letting the copper-skinned woman dig her heels in, the dark-haired woman built up her all her energies. She then /pushed/ the entire pool of poisonous Liquid right at the copper-skinned woman, releasing it at her arm.
Instinctively, the copper-skinned woman turned her whole arm into pure water-- a defense the dark-haired woman had used many times before, that would protect it against any Liquid-- but only sealed her fate this time. The dark-haired woman was ready and pushed a huge mass of pressurized Gas and shards of metal through the copper-skinned woman's Liquid arm, sending the Liquid splashing.
The copper-skinned woman took a second to glance at her own arm, and only then screamed.
The dark-haired woman tried to use her advantage to press on more, but her senses were blocked and she couldn't find any of her attackers without them. She had to find the red-eyed man eventually if she wanted to end the battle. But how could she if she could barely find a second of vision, all while being battered by the rest of them?
She continued to make Space between her and her attackers by erupting large plumes of dirt, which she pushed forward with huge gusts of wind.
She called on her sphere to give her something better, some steel shards--
Her sphere was not near her. She grasped for it again--
Nothing. She knew what had happened in an instant-- the freckled woman had teleported it somewhere far away. It was still connected to her, and made her much stronger, but without it near her she could ask it for no Elements. She called it back to her, but had no idea how far away it was and how long it would take for it to come back.
The confusion killed her focus on staying nimble in the Darkness. She bumped into a tree, and /yelped/ as something hit her in the shoulder. Even with steel skin, and a thick shield of air, a direct hit from the flying bullets thrown by the identical men pierced her.
She had to kill the red-eyed man soon if she even wanted to be able to defend herself. But how could she find him? As usual, she started with what she knew.
/He always was a coward... but he still liked to be on top.../
Her Mind lit up. She knew where he was. She moved two stones from the ground that she felt into her hand. Sidestepping, she jumped up and made a spiral case of airsteps, ascending. She felt prickly pines brush against her steel skin.
She broke through the Illusion of Darkness and saw a /flash/ of the stars. Only for a moment, of course. She jumped, hopped, twirled and fell, glancing upon different treetops as she had brief frames where the red-eyed man's veil of Darkness didn't catch her. In her palm, the two stones she had picked up scratched against each other astounding speed, making sparks fly. For a second, she saw a short figure crouched on the highest branch of a tree-- /she knew it./
Up here, she didn't need to worry about any Light powering the bearded man-- but it was what she could use to finally defeat that veil of Darkness.
She pushed a powerful gust of air through the sparked stones, and a fireball lit above her hand. At once, the Illusion of blackness broke and her vision was restored. Less than a tree's length away, the red-eyed man was crouched.
/That's it-- all this time-- you got him!/
The woman /blasted/ her fire forward, casting the red-eyed man in a blanket of fire.
She roasted him for what seemed like an eternity, balanced atop her step of pure air.
Finally, she let the fire shrink back to her hand. The treetops were still topped with flames, and she moved oxygen away from them to let it shrink.
But there was no skeleton.
/Fuck--/
The woman's eyes widened.
/An Illusion./
At once, she felt her body being /squeezed/-- She could make herself totally into Liquid or Gas, but that could destroy her body in one fell swoop-- and she didn't want what happened to the copper-skinned woman's arm to happen to her whole body.
She felt her body be pulled down to the ground-- and then stopped. The red-eyed man let her see the truth for a moment-- she had been pulled down by that massive man and flashed through one of the freckled woman's Portals, and now was face-to-face with those shimmering red eyes.
The red-eyed man grabbed her by the shoulders.
The dark-haired woman jerked-- but it was too late. She dissappeared from the world.


The dark-haired woman spun around rapidly, her fists readied. She was blinded in a blur of light gray, a heavenly light compared to the utter Darkness she had been in before. She stepped and /sunk/-- her heavy metal skin fell through gravel floor--
She shifted her feet, finding a stable position in the gravel, and shifting her skin back to flesh. She was on the side of a barren, rocky mountain, on a flat alcove. The environment was /lifeless/, and though there was a river on the mountain in the distance, it looked as if it did not flow.
She spun around instinctively, though there was no sound. The red-eyed man greeted her from high above.
"You are doomed-- this is my world, and you're never going to get out. You are dead-- now just accept it. I'll let you live a few minutes-- you can enjoy your last moments in peace," the red-eyed man said. "They say it's the last moments that really matter, and the surprises-- and for you this is both."
The dark-haired woman grit her teeth. "I won't let you kill me. Even if my whole life is just making it so you can't return here, to disadvantage you-- I'll fight you every time."
The red-eyed man clasped his lips. "I thought we could've reminsced over old times-- talk about our regrets, complain about /him/--"
The woman raised a hand, at loose rocks and boulders behind the man-- but they did not come loose as she expected.
The red man smiled at her, before dissappearing.
She turned around, looking for her silver sphere. It was nowhere to be found. She reached out at the apparent rocky mountain cliffside, expecting it to turn her skin. Her skin stayed flesh. She squeezed the gravel and grunted. Her skin stayed flesh.
She was powerless.
That warranted a scream at the vast dead hills behind her. The barren rocky highlands and grey smooth sky, stretched for the entire horizon, spoke back to her with utter silence.
She only had a moment before she heard the gravel behind her shift. The red-eyed man was back with the three tall, identical white men, and the /massive/ bearded man, whose feet clung to the side of the mountain, separately from the alcove where the rkxsest of them stood.
"As I was saying--," the red-eyed man cleared his throat. "But so be it."
The bearded man screamed-- he swung an arm the size of a small tree at the woman, who rolled into the gravel to avoid the attack.
She jumped down, her hands hanging off the cliff side opposite of the massive bearded man. Her brain had somehow told her body she was powerless-- she was red and sweaty with panic.
She looked below and dropped down, falling into a deep lunge and wincing. It may not have been matter, but it felt like it. She lunged into a quick sprint, only narrowly avoiding the large blurred bullets which came at her from the identical attackers above.
The massive bearded man /slammed/ down from above, shaking the cliff. The dark-haired woman pivoted like a panther. At least she didn't have to worry about surprise teleport attacks here, and the Space woman had wisely stayed behind.
It also appeared that the other Elemental woman had been left behind-- another smart move on the attacker's part, given that her only hope now was to wrestle control of the Elemental poisons in the other woman's posession.
"Honestly, just give up, Misun!" The red-eyed man shouted as the dark-haired woman ducked a swing from the massive bearded man and returned a kick to his abdomen. "You don't have your little utility belt. And this is a world of pure Mind. You don't have /any/ Elements to grab from."
The dark-haired woman snarled, jumping another blazing steel bolt from the identical attackers as she ran past the bearded man.
"Yeah. But you do," she spun and reached her arm out just as another steel bolt shot towards her. It /smashed/ into her arm-- sticking into her bone and sending a plume of blood and bone out on the other side of her forearm. She howled in agony, but from her arm her skin grew into steel.
A sinister smile appeared on the red-eyed man's face. "I always liked-- that you were disciplined enough to do the hardest things for the cause you believed in. But that was just meaningless pain. You can't beat us without an artifact, or without /real/ matter-- without options. And you forget-- this is my realm. I still have power here."
In an instant, her surroundings became utter Darkness-- even her to her ears.
She shuffled around, her mind wracking her about the possibility of falling of the cliff.
"You've always been a coward! Even here facing me with /nothing/ and you still need your minions to get the job done!"
There was no response. She was literally screaming into the void.
Two rough forces wrapped around each of her arms and /pulled./
She felt her body slow, her vicious twisting and fighting halting to a sad squirm. The identical attackers were using their powers, flowing through their whips, to slow her down.
She felt a hand against her smooth steel back-- and then didn't, her touch also being cast into Darkness. She had been cast into the void.
/It's over, Misun. Relax. You don't need to put up that hard shell anymore./
She heard the words as if they were everywhere, as if they were whispered directly into her soul, as if she was the only Mind in existence.
/Relax. This is what you've always wanted, isn't it? To stop thinking. To stop fighting./
She was fading away. She truly felt nothing, she thought nothing, she was...
And then she felt it all again. He eyes popped into that bright Light, with that bearded ogre drolling above her, with those devilish red eyes inches from her face. Her ears filled with the pounding of her heart and the gasp of her lungs, she felt three hard blinks, and more than anything, a sharp pain in her chest that made every fluid in her body flow towards it.
She was lying down and could barely peek her chin up, but she knew that it was that black dagger lodged in her heart. She collapsed, unable to move.
/You know how I got them to beat you? It's the same way I knew how to find you./ The same voice laughed. /You drill over and over, and you know every technique, but you always do things the same way, even after all this time./
Her skin started shifting to steel, from the edges of her arms up to her chest.
She could do it. Maybe it was soon enough to push the dagger out...
She always had the determination...


The freckled woman looked destressed at the dark-haired woman's half-steel corpse, the outer edges of her body chrome as if someone had melted a hole in the steel on her belly. The freckled woman was the only one who glanced back at it several times with nervous eyes, as the rest of the group was huddled under the moonlight, taking stock after the battle.
"What's the matter? You aren't-- isn't it good riddance?" the red-eyed man moved out of the group and said to the freckled woman, his slitted pupils moving back and forth over her face.
"I don't know," the freckled woman said. "It's been-- so long, and we knew this was how it was going to end-- but she's one of the only ones who knew all of us, you know? And now there's one less."
The red-eyed man laugh. "You always thought too much," his voice raised so the rest of the group could hear him. "If you don't think this is a total win, you're insane!"
"It wasn't a /total/ win," the massive man said. He had already shrunk quite a bit, and held up a hand that was only a feet or two across. "I lost my favorite finger."
"And I lost my arm," the copper-skinned woman motioned with her nub shoulder.
"And we lost... two of us," one of the identical men said, and the others nodded.
"Tsk, tsk," the red-eyed man said as he paced around the group. "Everyone says my eyes are red, but I've come to the conclusion their tint must actually be rose. Because it seems right now I'm the only one who can see... how beautiful things are gonna be for us."
The material inside the chrome orb, which followed the red-eyed man, shifted to gold. The red-eyed man smiled as his skin did the same.
